---
# Source: hpe-csi-driver/templates/x10000-nfs-csp.yaml
### AlletraMP X10000 NFS CSP Service ###
kind: Service
apiVersion: v1
metadata:
  name: alletrastoragemp-x10000-nfs-csp-svc
  namespace: hpe-storage
  labels:
    app: alletrastoragemp-x10000-nfs-csp-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: alletrastoragemp-x10000-nfs-csp
---
# Source: hpe-csi-driver/templates/x10000-nfs-csp.yaml
### CSP deployment ###
kind: Deployment
apiVersion: apps/v1
metadata:
  name: alletrastoragemp-x10000-nfs-csp
  namespace: hpe-storage
spec:
  selector:
    matchLabels:
      app: alletrastoragemp-x10000-nfs-csp
  replicas: 1
  template:
    metadata:
      labels:
        app: alletrastoragemp-x10000-nfs-csp
    spec:
      serviceAccountName: hpe-csp-sa
      priorityClassName: system-cluster-critical
      containers:
        - name: alletrastoragemp-x10000-nfs-csp
          image: "quay.io/balakroh/hpestorage/alletrastoragemp-x10000-nfs-csp:v1.0.0-beta-2410"
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: log-dir
              mountPath: /var/log
      volumes:
        - name: log-dir
          hostPath:
            path: /var/log
